### ISSUE TITLE
Freezes on typing stuff at the end of a file

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter-haskell#12]
The whole editor would freeze (and spike CPU usage to 99%) if I type some stuff **at the end of a file**.

I haven't been able to identify the exact sequence of actions to reproduce the freeze, because it would almost always freeze when I try to type anything.

After some tinkering I think the problem comes from the scanner.

**Comment by rewinfrey** [comment]
@banacorn thanks for filing this issue. @maxbrunsfeld and I did some work on the external scanner and uncovered a condition that could result in non-termination. Those changes have been pushed to master, and should prevent your Atom instance from freezing. Do you mind checking out the latest master and verifying if the infinite looping is still occurring for you?

**Comment by banacorn** [comment]
Thank you for looking into this! 
I've tried out the latest scanner but it still freezes after a few keystrokes 😢

**Comment by rewinfrey** [comment]
@banacorn This is definitely on our radar, but as I'm still working on adding more Haskell language support for its multitude of language extensions, I've not prioritized getting this working in Atom yet. Thank you for your patience.

**Comment by banacorn** [comment]
I want to fix this, but I can't locate the source of the problem.

Could it be the scanner? If so, then perhaps instead of adding new stuff, should we fix the non-termination first? 
Could it be tree-sitter or Atom? If so, then perhaps other packages that also rely on external scanners could face this problem, too?

**Comment by rewinfrey** [comment]
@banacorn it's my understanding Atom currently isn't configured to use the `get_column` API that `tree-sitter-haskell`'s external scanner depends on for parsing layout rules. This won't affect other external scanners because as of right now, `tree-sitter-haskell` is the only grammar that requires the `get_column` API (and is the motivation for why it was added to `tree-sitter`). @maxbrunsfeld please correct me if I'm misunderstanding!

@banacorn, unfortunately there are other problems with the external scanner not parsing some layout cases correctly. At this time I would say `tree-sitter-haskell` is still not stable enough to depend on for other packages and is still a WIP.

**Comment by clojj** [comment]
> @banacorn, unfortunately there are other problems with the external scanner not parsing some layout cases correctly. At this time I would say `tree-sitter-haskell` is still not stable enough to depend on for other packages and is still a WIP.

I am curious about the status of tree-sitter-haskell... are these issues resolvable in your opinion ?

**Comment by tek** [comment]
this applied to the version from before the rewrite, cannot reproduce it now.
