### ISSUE TITLE
Literate Haskell not supported

### ISSUE THREAD

**Issue by zenzike** [tree-sitter/tree-sitter-haskell#125]
It seems that Literate Haskell, as in `.lhs` files, are not supported.  In `lhs` files, every line is a comment unless the line is prepended with a `>` symbol, or between lines that say `\begin{code}` and `\end{code}`. Additionally, code that should not be compiled but should be highlighted is indicated in a line that starts with `<`, or between lines that say `\begin{spec}` and `\end{spec}`.

**Comment by ObserverOfTime** [comment]
What you need is a literate-haskell parser with the appropriate haskell injections.

**Comment by Martinsos** [comment]
> What you need is a literate-haskell parser with the appropriate haskell injections.

Do you mean embeds? From what I got (sorry if wrong I am new to treesitter), while we could have a `literate-haskell` parser and specify ranges for `haskell` parser in it, the problem is that in these ranges each line would start with `<` (or `>`), so it won't parse correctly with haskell ts grammar. Unless haskell ts grammar supported having `>` or `<` at the start of every line, which I assume it does not and will likely not support? If this is all so, any other idea how this could be done? Thanks a lot!
