### ISSUE TITLE
Haskell indentation rules

### ISSUE THREAD

**Issue by clojj** [tree-sitter/tree-sitter-haskell#2]
Running the test "function_declarations" with this broken corpus file
```
...
=================================================
Function Declarations With Let
=================================================

f = let y = x
x = 1
  in y

...
```
doesn't result in the expected indentation error.
Is correct indentation a goal for this grammar ? if so, could you point me to where this needs to be implemented ?

**Comment by rewinfrey** [comment]
👋 @clojj, thanks for opening this issue. This is definitely a bug and the grammar is intended to respect Haskell's [layout rules](https://www.haskell.org/onlinereport/haskell2010/haskellch10.html#x17-17800010.3).

To correctly identify and enforce the layout rules, the `grammar.js` file defines [`externals`](https://github.com/tree-sitter/tree-sitter-haskell/blob/1c16f3c9bb2552b7afdeb4b35716324bd58a641f/grammar.js#L37-L41). Those are special symbols used within productions like [`_declarations`](https://github.com/tree-sitter/tree-sitter-haskell/blob/1c16f3c9bb2552b7afdeb4b35716324bd58a641f/grammar.js#L71-L82). Those symbols are detected in `src/scanner.cc`'s [`scan`](https://github.com/tree-sitter/tree-sitter-haskell/blob/1c16f3c9bb2552b7afdeb4b35716324bd58a641f/src/scanner.cc#L50) method. The scanner is invoked whenever a production rule in `grammar.js` depends on a symbol in the `externals` list to help with detecting indentation or special sequences of characters that aren't expressible in a context free grammar.

The bug is in the [`let`](https://github.com/tree-sitter/tree-sitter-haskell/blob/1c16f3c9bb2552b7afdeb4b35716324bd58a641f/grammar.js#L282) production rule. Specifically, the `let` rule should be defined as:

```
    let: $ => seq(
      'let',
      choice(
        seq(
          '{',
          repeat(seq($._declaration, $._terminal)),
          '}'
        ),
        seq(
          $._layout_open_brace,
          repeat1(seq($._declaration, choice($._terminal, $._layout_semicolon))),
          $._layout_close_brace
        )
      ),
      $.in_clause
    )
```

However, the grammar is not smart enough to know when a function declaration stops and when the `in_clause` portion of the `let` production begins. I suspect to fix this, we'll want to add a new external symbol for detecting `in`, so we can correctly parse this example:

```
f = let x = 1 in y
```

Currently on a holiday weekend, but will look at fixing this Tuesday. In the meantime if you're curious and want to try fixing this PR's are welcome! I do realize there is a lot of context here that isn't well documented and many apologies for that. Thanks for taking a look and for your interest in this grammar!

cc/ @maxbrunsfeld

**Comment by clojj** [comment]
Instead of defining a new external symbol „in“ (if that is what you meant), wouldn’t it be possible to define some choice (or an alternative let form) that uses the existing in_clause as its termination ?

**Comment by clojj** [comment]
If I remove "prec.right( ... )" from "_declarations" rule, I get all tests green, including my added tests for these:
`f = let y = x
        z = 2
        x = 1 in y

f = let y = 42 in y
`

**Comment by clojj** [comment]
How can I explicitly (assert) in 'corpus' tests for ERRORs ?

**Comment by maxbrunsfeld** [comment]
@clojj You can definitely put `(ERROR)` in the tests. We usually don't because the details of *how* errors are parsed (like which tokens get wrapped in an `ERROR`) is up to the Tree-sitter library itself and is subject to change as we further optimize and improve the error recovery algorithms.

**Comment by clojj** [comment]
this works, thx

```
===================================================
Function Declarations With wrong indentation in Let
===================================================

f = let y = x
   z = 2
        x = 1
        in y

---

(module
  (function_declaration
    (function_head
      (function_identifier (variable)))
    (function_body
      (let
        (ERROR
          (function_declaration
            (function_head
              (function_identifier (variable)))
            (function_body (variable)))
          (function_declaration
            (function_head
              (function_identifier (variable)))
            (function_body
              (function_application (integer) (variable)))))
          (function_declaration
            (function_head (function_identifier (variable_symbol (MISSING))))
          (function_body (integer)))
      (in_clause (variable))))))

```

**Comment by maxbrunsfeld** [comment]
> Is correct indentation a goal for this grammar?

@clojj Successfully parsing all correct Haskell code is the goal. It's *not* necessarily a goal to produce an error for *all* incorrect code; if we parse some incorrect code without error, that's ok. Personally, I wouldn't recommend adding explicit tests that assert what errors we produce for the reasons I mentioned above.

**Comment by rewinfrey** [comment]
@clojj, thanks for your continued work here. So cool to see `tree-sitter-haskell` in use in your language-haskell plugin! Thanks also to @maxbrunsfeld for the remote 🍐 on the external scanner logic in https://github.com/tree-sitter/tree-sitter-haskell/commit/01ee480bd7e383e181a62c2ba422bd4f166fbddd. @clojj, your concern about detecting `in` and potentially creating conflicts with identifiers starting with `in` was a great catch, but is something we have done in other [grammars](https://github.com/tree-sitter/tree-sitter-javascript/blob/6a8829c57425215f2016c060d105a9a323935ad4/src/scanner.c#L99-L115). In this case, we ensured that the `in` would not be confused with an identifier starting with `in`, by using `iswalpha` (which checks that the character after `n` is a white space character).

@clojj, I further simplified the `let` production in https://github.com/tree-sitter/tree-sitter-haskell/commit/0fe1f72b4d773614d9da0c30a27203b80b25c325 to reuse the `_declarations` rule, which preserves layout rules for declarations. 👍 for pointing out that the `prec.right` around `_declarations` was no longer necessary. :bow:

@clojj, I tried to use your solution to parse the test case added in https://github.com/tree-sitter/tree-sitter-haskell/commit/1b4b01473dffb2129f647be891375720a61a4c5a, but received a parse error. I might not have configured the grammar exactly as you have locally, but it's a potential edge case to be aware of in your fork.

@clojj, the parse tree produced by the problematic example you've referenced:

```haskell
f = let y = x
   z = 2
        x = 1
        in y
```

Appears to be a little misleading. It correctly produces an error, but I don't think it's identifying the intended error. Specifically the `(ERROR...)` subtree includes the final function declaration which is not the location of the error. The final function declaration also has a `MISSING` node in its tree, which should not be the case.

I've run the same example on the updated grammar and it produces a tree that I think more closely matches what we'd expect:

```
(module [0, 0] - [4, 0]
  (function_declaration [0, 0] - [3, 12]
    (function_head [0, 0] - [0, 1]
      (function_identifier [0, 0] - [0, 1]
        (variable [0, 0] - [0, 1])))
    (function_body [0, 4] - [3, 12]
      (let [0, 4] - [3, 12]
        (ERROR [0, 8] - [2, 9]
          (function_declaration [0, 8] - [0, 13]
            (function_head [0, 8] - [0, 9]
              (function_identifier [0, 8] - [0, 9]
                (variable [0, 8] - [0, 9])))
            (function_body [0, 12] - [0, 13]
              (variable [0, 12] - [0, 13])))
          (function_declaration [1, 3] - [2, 9]
            (function_head [1, 3] - [1, 4]
              (function_identifier [1, 3] - [1, 4]
                (variable [1, 3] - [1, 4])))
            (function_body [1, 7] - [2, 9]
              (function_application [1, 7] - [2, 9]
                (integer [1, 7] - [1, 8])
                (variable [1, 8] - [2, 9])))))
        (function_declaration [2, 10] - [2, 13]
          (function_head [2, 10] - [2, 10]
            (function_identifier [2, 10] - [2, 10]
              (variable_symbol [2, 10] - [2, 10])))
          (function_body [2, 12] - [2, 13]
            (integer [2, 12] - [2, 13])))
        (in_clause [2, 13] - [3, 12]
          (variable [3, 11] - [3, 12]))))))
```

It's a bit hard to read and look at nesting, but the `(ERROR....)` portion of the tree closes over the second function declaration (`z = 2`), which is the source of the error because as you've rightly pointed out, violates Haskell's layout rules. The final function declaration is still a child of the `let` subtree, but otherwise represents a well formed function declaration (this is because tree-sitter attempts to produce its best guess for trees containing errors, and in this case assumed the final function declaration is still part of the `let` statement because it is followed by an `in_clause`).

@clojj if you have changes that you'd like to push upstream PR's are always welcome. For now, I will close this issue as the original example is now correctly producing an error, and `let` productions enforce layout rules correctly as best as we can tell at this time.
