### ISSUE TITLE
layout elements with implicit semicolon break queries

### ISSUE THREAD

**Issue by tek** [tree-sitter/tree-sitter-haskell#32]
When a semicolon is deduced from indent in the scanner, the next node is skipped when I use tree-sitter for neovim highlighting.

Example:

```haskell
import Foo.Bar
import Foo.Bar
```

In this case, only the first line is highlighted, and the second line doesn't even appear in the tree displayed by `:TSPlaygroundToggle`. However, with `tree-sitter parse`, it is correctly included in the tree.

On the other hand, with an explicit semicolon:

```haskell
import Foo.Bar;
import Foo.Bar
```

the second line is highlighted as well.

The scanner consumes the newline as part of the implicit semicolon. Maybe that's the problem?

@maxbrunsfeld @patrickt any advice?

**Comment by tek** [comment]
even though I have the `get_column` fix in my system treesitter, is it possible that neovim doesn't have it yet?

**Comment by tek** [comment]
ping @maxbrunsfeld

**Comment by tek** [comment]
ping again @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
I don't have very much context on the Neovim side of things, so I think you'll need to figure out:
* what version of Tree-sitter you're using in your build of Neovim
* if the bug is on the Neovim side of the Tree-sitter side

If the Tree-sitter version is current, and the bug is on the Tree-sitter side, we may need a minimal way to reproduce the bug outside of the context of Neovim.

**Comment by tek** [comment]
this is not present anymore in current nvim.
