### ISSUE TITLE
Support `OverloadedRecordDot`

### ISSUE THREAD

**Issue by ocharles** [tree-sitter/tree-sitter-haskell#97]
Right now `tree-sitter-haskell` parses `foo.bar` as if it's `foo . bar` - that is, the composition of `foo` and `bar` functions with the infix `.` operator. If `-XOverloadedRecordDot` is on, this should parse as accessing the field `bar` of the expression `foo`.

**Comment by tek** [comment]
We can't parse conditioned on extensions, but since the dot is already whitespace sensitive, I think it makes sense to default to parsing a projection for the no-whitespace case when the preceding expression is not a conid.
A cursory glance at the grammar suggests that this requires quite a bit of rearrangement of rules, so this is an opportunity to clean up a bit 🙂

**Comment by ocharles** [comment]
Fair enough! Note that you probably also want to parse `(.foo)` specially, too.

**Comment by tek** [comment]
please take a look, @ocharles : https://github.com/tree-sitter/tree-sitter-haskell/pull/98

**Comment by ocharles** [comment]
Thanks, I'm just rebuild Helix with this now - I'll report back!

**Comment by ocharles** [comment]
![image](https://user-images.githubusercontent.com/20878/224999723-7a3c88af-5175-4459-bf2b-5fac2899a662.png)

Neato!

**Comment by tek** [comment]
cool 🙂 let's merge it then

**Comment by ocharles** [comment]
Yep, I think everything is good here
